### ISSUE TITLE
Model is expecting 4 tensors as input while evaluating

### ISSUE THREAD

**Issue by pasrichashivam** [solaris33/EAST-tf2#1]
Hi,

In model.py file model requires 4 inputs as list.
`model = tf.keras.models.Model(inputs=[input_image, overly_small_text_region_training_mask, text_region_boundary_training_mask, target_score_map], outputs=[pred_score_map, pred_geo_map])
`
While running the eval.py file we are giving one tensor as input input images.
`score_map, geo_map = model.predict(img_resized[np.newaxis, :, :, :])`

which is giving below error
`ValueError: Layer model expects 4 inputs, but it received 1 input tensors. Inputs received: [<tf.Tensor 'input_1:0' shape=(None, 512, 512, 3) dtype=float32>]`

**Comment by solaris33** [comment]
Hi.

upgrade tensorflow version >= 2.2.0 will solve that issue.

thank you.

**Comment by anug7** [comment]
@solaris33 ,

I am getting the same error with tensorflow 2.4.0 as well.

`ValueError: Layer model expects 4 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor: shape=(8, 512, 512, 3), dtype=float32`

GPU used: RTX 3060Ti - 8GB

**Comment by khu834** [comment]
This appears to be a bug in the code, looks like the model in forward propagation only requires the `input_image`, the other 3 inputs `overly_small_text_region_training_mask`, `text_region_boundary_training_mask` and `target_score_map` are used only in the backpropagation.

A simple fix is to change https://github.com/solaris33/EAST-tf2/blob/db6c5d6c630e6fb2043b31726304047ff35a1096/model.py#L65

to 
```
model = tf.keras.models.Model(inputs=[input_image,], outputs=[pred_score_map, pred_geo_map])
```

This model input is then compatible with how it is called in `train.py` https://github.com/solaris33/EAST-tf2/blob/db6c5d6c630e6fb2043b31726304047ff35a1096/train.py#L40

where only a single input is provided, corresponding to the `input_images` batch

**Comment by anug7** [comment]
@khu834  ,
I figured it out. I didn't put it here. 
Thank you.
